### ISSUE TITLE
Review 1.1

### ISSUE THREAD

**Issue by katyhuff** [arfc/2019-ddca-journal-article#16]
I'll start reading the new version. In the meantime, see some high level comments for the later pages on the pdf version I had started to review in #4 . 
[2019-ddca.pdf](https://github.com/arfc/2019-ddca-journal-article/files/3795398/2019-ddca.pdf)

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/2019-ddca-journal-article/pull/17
