### ISSUE TITLE
Cover letter review

### ISSUE THREAD

**Issue by gwenchee** [arfc/2019-ddca-journal-article#27]
This issue can be closed after @katyhuff reviews the Nuclear Technology cover letter. 
[cover-letter.pdf](https://github.com/arfc/2019-ddca-journal-article/files/4060654/cover-letter.pdf)

**Comment by katyhuff** [comment]
Instead of 'the nuclear fuel cycle system' in the last paragraph, perhaps
'energy system transitions'?

**Comment by gwenchee** [comment]
Done!
